const data = {
  products: [
    {
      name: 'Handbook Of Mechanical Engineering Useful For Gate Ese Psus & Other Competitive Exams',
      category: 'GATE',
      image: '/images/book1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 272,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Shishir Kumar Persai (Author),Gk Publications (P) Ltd (Publisher",
    },
    {
      name: 'Land & Water Management Engineering Compiled For Jrf Srf Gate Net Ars',
      category: 'GATE',
      image: '/images/book2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 180,
      rating: 4.2,
      numReviews: 20,
      countInStock: 20,
      description: 'Na (Author),Jain Brothers (Publisher)',
    },
    {
      name: 'Gate Tutor 2021 Electrical Engineering : Code G481',
      category: 'GATE',
      isFeatured: true,
      image: '/images/book3.jpg',
      price: 290,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Prashant Bharti, Bhavin Juneja, Gaurav Goel (Author)',
    },
    {
      name: 'Gate 2022 Mechanical Engineering Chapter Wise 26 Years Solved Papers 1996-2021',
      category: 'GATE',
      isFeatured: true,
      image: '/images/book4.jpg',
      price: 320,
      rating: 4.5,
      numReviews: 35,
      countInStock: 20,
      description: 'Na (Author),Gk Publications (P) Ltd (Publisher)',
    },
    {
      name: 'Prestressed Concrete',
      category: 'GATE',
      isFeatured: true,
      image: '/images/book5.jpg',
      price: 195,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'N Krishna Raju (Author),Mcgraw Hill Education (Publisher)',
    },
    {
      name: 'Classic Pants',
      category: 'Pants',
      isFeatured: true,
      image: '/images/book6.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 18,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Gate Tutor 2021 Instrumentation Engineering : Code G480',
      category: 'Pants',
      isFeatured: true,
      image: '/images/book5.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Ankit Goel, Geetika (Author),Arihant Publications India Pvt Ltd (Publisher)',
    },
    {
      name: 'Gate 2022 Architecture & Planning Vol: 1',
      category: 'Pants',
      isFeatured: true,
      image: '/images/book6.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 18,
      countInStock: 20,
      description: ' Ar Jinisha Jain (Author),Gk Publications (P) Ltd (Publisher)',
    },
  ],
};
export default data;
